main:
  - name: Main
    url: /
    weight: 10
  - name: Papers
    url: /publications/
    weight: 20
  - name: LLM
    url: /events/
    weight: 30
  - name: ML/AI
    url: /blog/
    weight: 40
  - name: Biostatistics
    url: /projects/
    weight: 50
  - name: Cardiology
    url: /courses/
    weight: 60
  - name: Projects
    url: /myprojects/
    weight: 70
