main:
  - name: Main
    url: /
    weight: 10
  - name: Trials
    url: /trials/
    weight: 20
  - name: LLM
    url: /llm/
    weight: 30
  - name: ML/AI
    url: /ml-ai/
    weight: 40
  - name: Biostatistics
    url: /biostatistics/
    weight: 50
  - name: Cardiology
    url: /cardiology/
    weight: 60
  - name: Projects
    url: /myprojects/
    weight: 70
